from __future__ import annotations

class VersionInfo:
    @staticmethod
    def parse(s: str) -> VersionInfo: ...
    def bump_major(self) -> VersionInfo: ...
    def bump_minor(self) -> VersionInfo: ...
    def bump_patch(self) -> VersionInfo: ...
